"""Regression: TLS streaming server + pinned-client round-trip.

Spins up a small FastAPI app on a TLS port using the identity cert
generated by p2p_tls, then connects with a pinned client and verifies
that:

  * The TLS handshake succeeds with our self-signed cert.
  * The server's presented cert pubkey matches our identity pubkey
    (so peers can pin the cert against the value they already have
    in paired_devices / inventory cache).
  * A wrong-pin attempt is rejected after the handshake.

These pin the contract the streaming-port migration depends on.
"""
from __future__ import annotations

import asyncio
import base64
import socket
import ssl
import threading
import time

import pytest
import uvicorn
from fastapi import FastAPI

from backend import identity, p2p_tls


pytestmark = pytest.mark.smoke


def _free_port() -> int:
    """Pick an unused TCP port for the test server. Bind-then-close
    is racy in theory but fine in CI: 65k port range, single-test
    isolation."""
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


@pytest.fixture()
def isolated_identity_dir(tmp_path, monkeypatch):
    """Point identity + cert paths at a tmp dir so tests don't touch
    the real install's data/ directory."""
    monkeypatch.setattr(
        identity, "_IDENTITY_PATH", tmp_path / "identity.json",
    )
    monkeypatch.setattr(identity, "_CACHED", None)
    monkeypatch.setattr(
        p2p_tls, "_CERT_PATH", tmp_path / "identity-cert.pem",
    )
    monkeypatch.setattr(
        p2p_tls, "_CERT_KEY_PATH", tmp_path / "identity-cert-key.pem",
    )
    return tmp_path


def _start_test_tls_server(port: int) -> tuple[uvicorn.Server, threading.Thread]:
    """Spin up a tiny FastAPI app on a TLS port using our identity cert.

    Returns the (server, thread) pair so the caller can stop it
    cleanly. We use a thread rather than asyncio.run because the
    test runner already owns the event loop.
    """
    app = FastAPI()

    @app.get("/ping")
    async def _ping():
        return {"ok": True}

    cert_path, key_path = p2p_tls.ensure_identity_cert()
    config = uvicorn.Config(
        app, host="127.0.0.1", port=port,
        log_level="warning", lifespan="off",
        ssl_certfile=str(cert_path), ssl_keyfile=str(key_path),
    )
    server = uvicorn.Server(config)

    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()

    # Wait for the server to bind. uvicorn doesn't expose a direct
    # ready event, so we poll the server's `started` flag.
    for _ in range(100):
        if server.started:
            return server, thread
        time.sleep(0.05)
    raise RuntimeError("TLS test server failed to start within 5 s")


def test_tls_server_presents_identity_cert(isolated_identity_dir):
    """End-to-end: the TLS server uses the identity cert; a client
    extracts the cert pubkey and confirms it matches the install's
    identity pubkey. This is the foundation that pinning depends on."""
    me = identity.get_identity()
    port = _free_port()
    server, _ = _start_test_tls_server(port)
    try:
        # Open a raw TLS socket and pull the presented cert.
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        with socket.create_connection(("127.0.0.1", port), timeout=5) as sock:
            with ctx.wrap_socket(sock, server_hostname=None) as ssock:
                cert_der = ssock.getpeercert(binary_form=True)
        assert cert_der, "server presented no cert at all"
        # Pin must extract to our install's Ed25519 pubkey.
        extracted = p2p_tls.cert_pubkey_b64(cert_der)
        assert extracted == me.public_key_b64
        # And the verify_peer_cert helper accepts it.
        assert p2p_tls.verify_peer_cert(cert_der, me.public_key_b64) is True
    finally:
        server.should_exit = True


def test_tls_server_pin_mismatch_rejects(isolated_identity_dir):
    """A client with a WRONG expected pin must reject the cert
    even though the TLS handshake itself completes. This is the
    contract that prevents an attacker who substitutes a different
    self-signed cert from passing as a known peer."""
    port = _free_port()
    server, _ = _start_test_tls_server(port)
    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        with socket.create_connection(("127.0.0.1", port), timeout=5) as sock:
            with ctx.wrap_socket(sock, server_hostname=None) as ssock:
                cert_der = ssock.getpeercert(binary_form=True)
        wrong_pin = base64.b64encode(b"\x00" * 32).decode("ascii")
        assert p2p_tls.verify_peer_cert(cert_der, wrong_pin) is False
    finally:
        server.should_exit = True
